version: '3.4'
services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      VERSION: LATEST
      SERVER_NAME: "Nowak Ninja Minecraft Server"
      MAX_PLAYERS: 5
      LEVEL_NAME: "Deweloperka"
      GAMEMODE: survival
      DIFFICULTY: normal
      WHITE_LIST: "false"
      PLAYER_IDLE_TIMEOUT: 30
    ports:
      - 19132:19132/udp
    stdin_open: true
    tty: true
    volumes:
      - bds:/data
      - ./whitelist.json:/data/whitelist.json
      - ./permissions.json:/data/permissions.json
    restart: always
volumes:
  bds: {}
  whitelist.json: {}
  permissions.json: {}
